### PR TITLE
Symfony 6.0 compatibility

### PR DESCRIPTION
**Pull request by firstred**
This PR makes the bundle compatible with Symfony 6.0 by updating the dependencies in `composer.json`.
No code changes are required as far as I can see.

### CODE REVIEW

**Comment by Rastusik** [comment]
hi @firstred ! thank you for the contribuition! please make the required checks work and I'll merge the PR. thank you ;)

**Comment by firstred** [comment]
Thanks for the fast reply! I believe it needs approval before it can run the checks?

**Comment by Rastusik** [comment]
yapp, sorry ... there still are conflicts in the composer.lock file ... seems to me like you just did `composer update`, which is not the proper way to update concrete dependencies. you have to manually run `composer require "symfony/config":"^4.1|^5.0|^5.1|^6.0" (--dev if needed)` for each dependency change... and the changes need to be made from the newest master commit, so no conflicts will occur that way. Sorry for not making this myself, but I'm still on vacation.

**Comment by Rastusik** [comment]
yeah and the commands need to be run from the php 7.4 docker container in the repository, so the bundle stays compatible with php 7.4

**Comment by Rastusik** [comment]
Hi @firstred , was there any reason for you to close the PR?

**Pull request closed without merging**
