### PR TITLE
Removed deprecations

### PR DESCRIPTION
**Pull request by thomaspicquet**
Suggested method by the doctrine team to check a connection:
https://github.com/doctrine/dbal/blob/0a5bac1c2ce1d1b68944541e6a74e2325d274847/tests/Doctrine/Tests/DBAL/Functional/Connection/ConnectionLostTest.php#L31-L51

### CODE REVIEW

**Comment by Rastusik** [comment]
Hi @thomaspicquet ! Thank you for the pull request. Since you're the first one, we still don't have automations with github actions on this repository and I just found out, that your updated composer.lock file doesn't work with PHP 7.4. Have you tried running unit tests in the docker-compose provided by this package?

For now, we need this bundle to be runnable on PHP 7.4, if you'll be able to run it on 8.0, good for you :) ... BTW, what was the purpose of the composer update?

**Comment by thomaspicquet** [comment]
Hey @Rastusik, the current swoole app I'm working on uses PHP8 so I have the latest version of Doctrine. I can make some changes to make sure it works with PHP 7.4 tomorrow 😊

**Comment by thomaspicquet** [comment]
@Rastusik this is ready for your review!

**Comment by Rastusik** [comment]
Hey @thomaspicquet thank you again for your effort. I made the changes myself because I needed to update this package, it will be released any moment

**Comment by thomaspicquet** [comment]
@Rastusik sounds good, sorry I didnt get the time to fix the tests.

**Comment by Rastusik** [comment]
@thomaspicquet no worries, you still saved us some time ;)

**Pull request closed without merging**
